nodeLinker: node-modules

enableImmutableInstalls: false

packageExtensions:
  react-resizable@*:
    peerDependencies:
      react-dom: '*'
    peerDependenciesMeta:
      react-dom:
        optional: false
